data_path: "data/PoolBoiling-SubCooled-FC72-2D/downsampled_redimensionalized/"
device: "cuda"
batch_size: 8
save_path: "models/PoolBoiling-SubCooled-FC72-2D/"
discard_first: 20
wandb: "True"

model:
  name: "UNet_classic"
  tw: 5
  use_coords: True

training:
  files: ["Twall-79.hdf5", "Twall-81.hdf5", "Twall-85.hdf5", "Twall-90.hdf5", "Twall-95.hdf5", "Twall-98.hdf5", "Twall-103.hdf5", "Twall-106.hdf5", "Twall-110.hdf5"]
  epochs: 500
  learning_rate: 0.001
  max_unrolling: 2

validation:
  files: ["Twall-100.hdf5"]
  gif_length: 50
  makegif_val: True
  makegif_train: True
  makeplot_val: True
  makeplot_train: True
