data_path: "data/PoolBoiling-SubCooled-FC72-2D/downsampled_redimensionalized/"
device: "cuda"
batch_size: 32
save_path: "models/PoolBoiling-SubCooled-FC72-2D/"

modelname: "UNet2D_DS"

training:
  files: ["Twall-79.hdf5", "Twall-81.hdf5", "Twall-85.hdf5", "Twall-90.hdf5", "Twall-95.hdf5", "Twall-98.hdf5", "Twall-103.hdf5", "Twall-106.hdf5", "Twall-110.hdf5"]
  epochs: 300
  learning_rate: 0.001

validation:
  files: ["Twall-100.hdf5"]