data_path: "/data/PoolBoiling-SubCooled-FC72-2D/"
device: "cuda"
batch_size: 32


training:
  files: ["Twall-79.h5py", "Twall-81.h5py", "Twall-85.h5py", "Twall-90.h5py", "Twall-95.h5py", "Twall-98.h5py", "Twall-103.h5py", "Twall-106.h5py", "Twall-110.h5py", ]
  epochs: 10
  learning_rate: 0.001

validation:
  files: ["Twall-100.h5py"]