data_path: "data/PoolBoiling-SubCooled-FC72-2D-0.1/redim_DS4/"
device: "cuda"
batch_size: 16
save_path: "models/PoolBoiling-SubCooled-FC72-2D-0.1/"
save_on: 0
discard_first: 200
wandb: 1 #"True"

model:
  name: "UNet_classic"
  tw: 5
  use_coords: True
  prop: [64, 4, 'gelu']

training:
  files: ["Twall-79.hdf5", "Twall-81.hdf5", "Twall-85.hdf5", "Twall-88.hdf5", "Twall-90.hdf5", "Twall-92.hdf5", "Twall-95.hdf5", "Twall-97.hdf5", "Twall-98.hdf5", "Twall-103.hdf5", "Twall-106.hdf5", "Twall-108.hdf5", "Twall-110.hdf5"]
  epochs: 300
  learning_rate: 0.001
  max_unrolling: 5

validation:
  files: ["Twall-100.hdf5"]
  gif_length: 300
  makegif_val: True
  makeplot_val: True
  makeplot_train: True
  makegif_vertical: False
