data_path: "data/PoolBoiling-SubCooled-FC72-2D-0.1/redim_DS4/"
device: "cuda"
save_path: "models/PoolBoiling-SubCooled-FC72-2D-0.1/"
save_on: 0
wandb: 1 #"True"

loader:
  num_workers: 4
  pin_memory: True
  prefetch_factor: 4
  discard_first: 200
  batch_size: 8

model:
  name: "UNet_classic"
  tw: 5
  use_coords: True
  prop: [64, 3, 'gelu']

training:
  files: ["Twall-79.hdf5", "Twall-81.hdf5", "Twall-85.hdf5", "Twall-88.hdf5", "Twall-90.hdf5", "Twall-92.hdf5", "Twall-95.hdf5", "Twall-97.hdf5", "Twall-98.hdf5", "Twall-102.hdf5", "Twall-103.hdf5", "Twall-106.hdf5", "Twall-108.hdf5", "Twall-110.hdf5"]
  epochs: 300
  init_learning_rate: 1e-3
  weight_decay: 1e-2
  max_unrolling: 4
  pushforward_step: 20

validation:
  files: ["Twall-100.hdf5"]
  gif_length: 300
  makegif_val: True
  path_gif: "output/temp_gif3.gif"
  makeplot_val: False
  makeplot_train: True
  path_plot: "output/temp_plot3.png"
  makegif_vertical: False
