data_path: "data/PoolBoiling-SubCooled-FC72-2D-0.1/redim_DS4/"
device: "cuda"
save_path: "models/PoolBoiling-SubCooled-FC72-2D-0.1/"
save_on: 0
wandb: 1 #"True"
wandb_name: "hpc_01DS4_4"

loader:
  num_workers: 4
  pin_memory: True
  prefetch_factor: 2
  discard_first: 200
  batch_size: 64

model:
  name: "UNet_classic"
  tw: 5
  use_coords: True
  prop: [48, 3, 'gelu']

training:
  files: ["Twall-79.hdf5", "Twall-81.hdf5", "Twall-85.hdf5", "Twall-88.hdf5", "Twall-90.hdf5", "Twall-92.hdf5", "Twall-95.hdf5", "Twall-97.hdf5", "Twall-98.hdf5", "Twall-102.hdf5", "Twall-103.hdf5", "Twall-106.hdf5", "Twall-108.hdf5", "Twall-110.hdf5"]
  epochs: 300
  init_learning_rate: 2e-3
  weight_decay: 1e-3
  max_unrolling: 2
  pushforward_step: 10
  transform: 0

validation:
  files: ["Twall-100.hdf5"]
  gif_length: 300
  makegif_val: True
  path_gif: "output/temp_gif4.gif"
  makeplot_val: False
  makeplot_train: True
  path_plot: "output/temp_plot4.png"
  makegif_vertical: False
  rollout_length: 150
  pushforward_val: 4
  viz_step: 10
