epochs: 300
batch_size: 64
init_lr: 1.0e-4
patience: 10
weight_decay: 0.0 #1.0e-3
inj_noise: False
train_ratio: 0.8
normalize: False
pin_memory: False
forward_steps_loss: 3

plottrain_out: "plot_train_nonorm.png"
plotval_out: "plot_val_nonorm.png"
anim_out: "anim_out_nonorm.gif"