epochs: 300
batch_size: 8
init_lr: 1.0e-3
patience: 10
weight_decay: 1.0e-3
inj_noise: False
train_ratio: 0.8
normalize: False
pin_memory: True

plottrain_out: "plot_train_nonorm.png"
plotval_out: "plot_val_nonorm.png"
anim_out: "anim_out_nonorm.gif"