epochs: 300
batch_size: 8
init_lr: 1.0e-3
patience: 10
weight_decay: 1.0e-3
inj_noise: False
train_ratio: 0.8
normalize: True
pin_memory: True

plottrain_out: "plot_train.png"
plotval_out: "plot_val.png"
anim_out: "anim_val.gif"